### ISSUE TITLE
What makes something SPOON?

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/spoondetector#6]
What makes something SPOON?

**Comment by Thunder33345** [comment]
if it's not PMMP
feel free to create a spoon detector for your variance of forks
it's made to assist developers in getting complains and help request for cores they dont support

**Comment by falkirks** [comment]
More technically in the context of this plugin, it is a derivative version of pmmp, which uses the same API versions to force plugins built for pmmp to load regardless of whether they are properly supported.
